export const homeProjectUpdateModalScript = [
'async function openProjectCompatibilityModal(project, detailOverlay = null) {',
  '  if (!project?.builtForReferenceVersionId) { showToast("这个项目还没有填写制作时使用的角色卡版本", "warning"); return; }',
  '  let references = [];',
  '  try {',
  '    const data = await fetchCharacterReferences();',
  '    references = Array.isArray(data?.references) ? data.references : [];',
  '  } catch (error) { showToast("角色卡版本加载失败: " + error.message, "error"); return; }',
  '  const reference = references.find(item => Array.isArray(item.versions) && item.versions.some(version => version.id === project.builtForReferenceVersionId));',
  '  if (!reference) { showToast("找不到这个项目使用的角色卡版本", "error"); return; }',
  '  const builtVersion = reference.versions.find(version => version.id === project.builtForReferenceVersionId);',
  '  if (!builtVersion) return;',
  '  const versions = [...reference.versions].filter(version => Number(version.versionOrdinal) >= Number(builtVersion.versionOrdinal)).sort((a, b) => Number(a.versionOrdinal) - Number(b.versionOrdinal));',
  '  const testedOptions = [`<option value="">还没有测试更新版本</option>`, ...versions.map(version => `<option value="${escapeHtml(version.id)}"${version.id === project.testedThroughReferenceVersionId ? " selected" : ""}>${escapeHtml(reference.name)} / ${escapeHtml(version.versionLabel)}</option>`)].join("");',
  '  const latestVersion = [...reference.versions].sort((a, b) => Number(b.versionOrdinal) - Number(a.versionOrdinal))[0] || builtVersion;',
  '  const html = `<form id="compatibilityMetadataForm" class="project-form compatibility-form"><div class="project-form-section"><div class="compatibility-section-head"><h3>角色卡版本</h3><p>这里记录这个 DLC 已经测试过哪些角色卡版本，不会修改 DLC 内容。</p></div><div class="project-form-grid"><div class="form-group"><label>制作时用的版本</label><input value="${escapeHtml(reference.name)} / ${escapeHtml(builtVersion.versionLabel)}" disabled></div><div class="form-group"><label>当前最新版本</label><input value="${escapeHtml(reference.name)} / ${escapeHtml(latestVersion.versionLabel)}" disabled></div><div class="form-group project-form-field--wide"><label>已测试可用到</label><select id="testedThroughReferenceVersionId">${testedOptions}</select><div class="form-hint">只有你真的用这个版本测试过，才选择它。</div></div><label class="taxonomy-chip"><input type="checkbox" id="compatibilityConfirmed"><span>我已经用这个版本测试过</span></label><label class="taxonomy-chip"><input type="checkbox" id="knownIncompatible"${project.compatibilityKnownIncompatible ? " checked" : ""}><span>这个版本不能正常使用</span></label><div class="form-group project-form-field--wide"><label>备注</label><textarea id="compatibilityNote" rows="4" maxlength="500" placeholder="可选：写下测试结果或已知问题">${escapeHtml(project.compatibilityNote || "")}</textarea></div></div></div><div class="project-form-footer"><button type="submit" class="btn btn-primary form-submit-btn"><i class="fas fa-check"></i> 保存</button></div></form>`;',
  '  const overlay = openModal(html, `<i class="fas fa-shield-halved"></i> 角色卡版本`);',
  '  overlay.classList.add("compatibility-modal");',
  '  const form = overlay.querySelector("#compatibilityMetadataForm");',
  '  form.onsubmit = async event => {',
  '    event.preventDefault();',
  '    const testedThroughReferenceVersionId = form.querySelector("#testedThroughReferenceVersionId")?.value || null;',
  '    const knownIncompatible = Boolean(form.querySelector("#knownIncompatible")?.checked);',
  '    const confirmed = Boolean(form.querySelector("#compatibilityConfirmed")?.checked);',
  '    const note = form.querySelector("#compatibilityNote")?.value?.trim() || null;',
  '    if (testedThroughReferenceVersionId && !knownIncompatible && !confirmed) { showToast("请先勾选「我已经用这个版本测试过」", "warning"); return; }',
  '    const submit = form.querySelector(".form-submit-btn");',
  '    const restore = setButtonLoading(submit, "保存中");',
  '    try {',
  '      await updateProjectCompatibility(project.id, { testedThroughReferenceVersionId, knownIncompatible, note });',
  '      showToast("已更新角色卡版本状态");',
  '      overlay.remove();',
  '      if (detailOverlay?.isConnected) detailOverlay.remove();',
  '      await showProjectDetail(project);',
  '    } catch (error) { showToast("角色卡版本更新失败: " + error.message, "error"); } finally { restore(); }',
  '  };',
  '}',
  '',
  'function serializeLegacyProjectUpdateEntry(entry) {',
  '  try { return JSON.stringify(entry || {}, null, 2); } catch (_) { return String(entry || ""); }',
  '}',
  '',
  'function buildLegacyProjectUpdateReviewDiff(diff) {',
  '  const makeChanges = (entries, status, kind) => (Array.isArray(entries) ? entries : []).map((entry, index) => {',
  '    const entryKey = String(entry?.entryKey || entry?.id || entry?.uid || `${kind}:${index}`);',
  '    const changedFields = status === "modified" ? [] : Object.keys(entry || {}).filter(key => key !== "entryKey" && key !== "id").sort();',
  '    const reviewText = serializeLegacyProjectUpdateEntry(entry);',
  '    if (status === "deleted") return { status, entryKey, changedFields, previous: entry, previousReviewText: reviewText };',
  '    return { status, entryKey, changedFields, current: entry, currentReviewText: reviewText };',
  '  });',
  '  const worldbook = [',
  '    ...makeChanges(diff?.added?.worldbookEntries, "added", "worldbook"),',
  '    ...makeChanges(diff?.modified?.worldbookEntries, "modified", "worldbook"),',
  '    ...makeChanges(diff?.removed?.worldbookEntries, "deleted", "worldbook"),',
  '  ];',
  '  const regex = [',
  '    ...makeChanges(diff?.added?.regexEntries, "added", "regex"),',
  '    ...makeChanges(diff?.modified?.regexEntries, "modified", "regex"),',
  '    ...makeChanges(diff?.removed?.regexEntries, "deleted", "regex"),',
  '  ];',
  '  const all = [...worldbook, ...regex];',
  '  const summary = all.reduce((counts, change) => { counts[change.status] += 1; return counts; }, { added: 0, modified: 0, deleted: 0 });',
  '  return { mode: "update", legacy: true, summary: { ...summary, unchanged: 0, changed: all.length, total: all.length }, worldbook, regex };',
  '}',
  '',
  'function resolveProjectUpdateReviewDiff(diff) {',
  '  if (diff?.reviewDiff?.mode === "update") return { ...diff.reviewDiff, legacy: false };',
  '  return buildLegacyProjectUpdateReviewDiff(diff || {});',
  '}',
  '',
  'function renderProjectUpdateHeader(project, chosenBook = null) {',
  '  const localMeta = chosenBook ? getLocalProjectInstallations(project.id).find(item => item.worldbookName === chosenBook) : getLocalProjectMeta(project.id);',
  '  const installedVersion = String(localMeta?.localVersion || project?.localVersion || "已安装版本");',
  '  const targetVersion = String(project?.version || project?.versionLabel || "最新版");',
  '  const author = getAuthorName(project);',
  '  const type = getProjectTypeDisplayLabel(project);',
  '  return `<section class="update-project-head"><div class="update-project-head-main"><strong>${escapeHtml(project?.name || "未命名项目")}</strong><span>${escapeHtml(author)} · ${escapeHtml(type)}</span></div><div class="update-project-version"><code>${escapeHtml(installedVersion)}</code><i class="fas fa-arrow-right"></i><code>${escapeHtml(targetVersion)}</code></div></section>`;',
  '}',
  '',
  'function renderDiffGroup(title, icon, worldbookEntries, regexEntries) {',
  '  const hasWorldbook = Array.isArray(worldbookEntries) && worldbookEntries.length > 0;',
  '  const hasRegex = Array.isArray(regexEntries) && regexEntries.length > 0;',
  '  if (!hasWorldbook && !hasRegex) return "";',
  '  const worldbookHtml = hasWorldbook ? renderDetailSection("世界书条目", "fa-scroll", worldbookEntries, renderDetailEntry, "") : "";',
  '  const regexHtml = hasRegex ? renderDetailSection("正则列表", "fa-code", regexEntries, renderRegexEntry, "") : "";',
  '  return `<div class="update-diff-group"><div class="detail-section-title"><span><i class="fas ${icon}"></i> ${title}</span></div>${worldbookHtml}${regexHtml}</div>`;',
  '}',
  '',
  'function openProjectUpdateModal(project, resolvedDiff, targetWorldbookName = null, approvedDuplicates = null) {',
  '  const installedBooks = getLocalProjectInstallations(project.id).filter(item => item.worldbookName);',
  '  const selected = targetWorldbookName ? installedBooks.find(item => item.worldbookName === targetWorldbookName) : getLocalProjectMeta(project.id);',
  '  const order = compareProjectVersions(project.version, selected?.localVersion);',
  '  if (order === -1) { showToast("远端版本 " + project.version + " 比本地 " + selected.localVersion + " 旧，已停止更新，避免降级", "warning"); return; }',
  '  if (order === null && !selected?.mixedVersions) { showToast("无法确认本地或远端版本，请重新扫描后再更新", "warning"); return; }',
  '  if (installedBooks.length > 1 && approvedDuplicates === null) {',
  '    const choices = installedBooks.map(item => `<button class="btn btn-outline" data-duplicate-keep="${escapeHtml(item.worldbookName)}">保留并更新 ${escapeHtml(item.worldbookName)}，删除其他副本</button>`).join("");',
  '    const overlay = openModal(`<p>发现 ${installedBooks.length} 处相同 DLC：${installedBooks.map(item => `${escapeHtml(item.worldbookName)}（版本 ${escapeHtml(item.localVersion || "未知")}）`).join("、")}。请选择唯一保留的位置。更新验收通过后才删除其他副本。</p><div class="update-modal-actions duplicate-install-actions">${choices}<button class="btn btn-outline" data-duplicate-cancel>取消更新</button></div>`, "确认重复安装位置");',
  '    overlay.querySelector("[data-duplicate-cancel]")?.addEventListener("click", () => overlay.remove());',
  '    overlay.querySelectorAll("[data-duplicate-keep]").forEach(button => button.addEventListener("click", async () => {',
  '      const keep = button.dataset.duplicateKeep;',
  '      const approvals = installedBooks.filter(item => item.worldbookName !== keep).map(item => ({ worldbookName: item.worldbookName, localVersion: item.localVersion || null, entryCount: item.entryCount }));',
  '      const restore = setButtonLoading(button, "读取选定位置");',
  '      try { const diff = await requestProjectDiff(project.id, project.version, keep); overlay.remove(); openProjectUpdateModal(project, diff, keep, approvals); }',
  '      catch (error) { showToast(error.message, "error"); } finally { restore(); }',
  '    }));',
  '    return;',
  '  }',
  '  const chosenBook = targetWorldbookName || (installedBooks.length === 1 ? installedBooks[0].worldbookName : null);',
  '  if (installedBooks.length > 1 && !chosenBook) { showToast("这个 DLC 安装在多本世界书，请到「订阅 / 已安装」选择具体一份再更新", "warning"); return; }',
  '  const diff = resolvedDiff || getProjectUpdateDiff(project.id) || {',
  '    added: { worldbookEntries: [], regexEntries: [] },',
  '    modified: { worldbookEntries: [], regexEntries: [] },',
  '    removed: { worldbookEntries: [], regexEntries: [] },',
  '  };',
  '  const reviewDiff = resolveProjectUpdateReviewDiff(diff);',
  '  const changedCount = Number(reviewDiff?.summary?.changed || 0);',
  '  const legacyNotice = reviewDiff.legacy ? `<div class="update-diff-legacy-notice"><i class="fas fa-circle-info"></i><span>当前使用的 Workshop 脚本版本较旧，这次只能显示更新后的内容；更新脚本后可看到完整前后差异。</span></div>` : "";',
  '  const noContentChange = changedCount === 0 ? `<div class="update-diff-empty-state"><i class="fas fa-circle-check"></i><span>版本有更新，但世界书和正则内容没有检测到变化。</span></div>` : "";',
  '  const bodyHtml = [',
  '    `<div class="update-modal">${renderProjectUpdateHeader(project, chosenBook)}`,',
  '    chosenBook ? `<p class="update-target-worldbook"><i class="fas fa-book"></i>更新位置：${escapeHtml(chosenBook)}</p>` : "",',
  '    `<div class="update-modal-lead">对比当前已安装版本与新版。</div>`,',
  '    legacyNotice,',
  '    renderProjectUpdateDiffSummary(reviewDiff),',
  '    renderProjectUpdateDiffSection("世界书变化", "fa-scroll", reviewDiff.worldbook, "worldbook"),',
  '    renderProjectUpdateDiffSection("正则变化", "fa-code", reviewDiff.regex, "regex"),',
  '    noContentChange,',
  '    `<div class="update-modal-actions"><button class="btn btn-outline" data-update-cancel>取消</button><button class="btn btn-primary" data-update-confirm>确认更新</button></div></div>`,',
  '  ].join("");',
  '  const overlay = openModal(bodyHtml, `<i class="fas fa-arrows-rotate"></i> 更新项目`);',
  '  overlay.classList.add("project-update-modal");',
  '  overlay.querySelector("[data-update-cancel]")?.addEventListener("click", () => overlay.remove());',
  '  overlay.querySelector("[data-update-confirm]")?.addEventListener("click", async event => {',
  '    const manageOriginalConflicts = await chooseOriginalConflictInstallManagement(project);',
  '    if (manageOriginalConflicts === null) return;',
  '    const button = event.currentTarget;',
  '    const restore = setButtonLoading(button, "准备更新");',
  '    try {',
  '      await confirmProjectUpdate(project.id, project.version, manageOriginalConflicts, chosenBook, approvedDuplicates || []);',
  "      showToast('已发送更新请求', 'info');",
  '      overlay.remove();',
  '    } catch (error) {',
  "      showToast('更新失败: ' + (error?.message || String(error)), 'error');",
  '    } finally {',
  '      restore();',
  '    }',
  '  });',
  '}',
  '',
  "async function loadProjectOriginalConflictItems(project) {",
  "  const requestedNames = Array.isArray(project?.originalConflictEntryNames) ? project.originalConflictEntryNames.map(String).map(name => name.trim()).filter(Boolean) : [];",
  "  if (!project?.conflictsWithOriginal) return { requestedNames, items: [], complete: true };",
  "  if (!requestedNames.length) return { requestedNames, items: [], complete: false };",
  "  const targets = Array.isArray(project?.originalConflictTargets) && project.originalConflictTargets.length === requestedNames.length",
  "    ? project.originalConflictTargets : null;",
  "  const items = requestedNames.map((displayName, index) => ({",
  "    displayName, kind: targets?.[index]?.displayName === displayName ? targets[index].kind : null",
  "  }));",
  "  return { requestedNames, items, complete: true };",
  "}",
  "",
  "async function chooseAmbiguousOriginalRegexes(ambiguities) {",
  "  const sections = ambiguities.map((item, index) =>",
  "    '<fieldset class=\"original-regex-choice-group\" data-regex-choice-index=\"' + index + '\">' +",
  "    '<legend>' + escapeHtml(item.displayName || '原版 Regex') + '</legend>' +",
  "    '<p>找到 ' + item.candidates.length + ' 条同名正则，请核对 ID，只选择要停用的一条。</p>' +",
  "    item.candidates.map((candidate, i) =>",
  "      '<label class=\"original-regex-choice-item\">' +",
  "      '<input type=\"radio\" name=\"originalRegexChoice' + index + '\" value=\"' + escapeHtml(candidate.regexId) + '\">' +",
  "      '<span>' + escapeHtml(candidate.displayName) +",
  "      ' · ' + (candidate.enabled ? '当前已启用' : '当前已停用') +",
  "      '<small>ID：' + escapeHtml(candidate.regexId) + '</small></span></label>').join('') +",
  "    '</fieldset>').join('');",
  "  const body = '<div class=\"install-conflict-consent\">' +",
  "    '<p>部分原版 Regex 名称重复，工坊不能替你猜测。请检查 ID 再确认，或取消后自行关闭。</p>' +",
  "    sections +",
  "    '<div class=\"install-conflict-actions\">' +",
  "    '<button class=\"btn btn-outline\" type=\"button\" data-regex-choice-cancel>返回</button>' +",
  "    '<button class=\"btn btn-primary\" type=\"button\" data-regex-choice-confirm>确认选择</button></div></div>';",
  "  const overlay = openModal(body, '选择需要关闭的原版正则');",
  "  return new Promise(resolve => {",
  "    let settled = false;",
  "    const finish = value => {",
  "      if (settled) return;",
  "      settled = true;",
  "      if (overlay.isConnected) overlay.remove();",
  "      resolve(value);",
  "    };",
  "    overlay.querySelector('[data-regex-choice-cancel]')?.addEventListener('click', () => finish(null));",
  "    overlay.querySelector('.close-btn')?.addEventListener('click', () => finish(null), { once:true });",
  "    overlay.addEventListener('click', event => { if (event.target === overlay) finish(null); });",
  "    overlay.querySelector('[data-regex-choice-confirm]')?.addEventListener('click', () => {",
  "      const choices = [];",
  "      for (const [index, item] of ambiguities.entries()) {",
  "        const input = overlay.querySelector('input[name=\"originalRegexChoice' + index + '\"]:checked');",
  "        if (!input) { showToast('请为每条同名正则选择一个目标', 'warning'); return; }",
  "        choices.push({ referenceItemId: item.referenceItemId, regexId: input.value });",
  "      }",
  "      finish(choices);",
  "    });",
  "  });",
  "}",
  "async function chooseOriginalConflictInstallManagement(project) {",
  "  const resolved = await loadProjectOriginalConflictItems(project);",
  "  const requestedNames = resolved.requestedNames;",
  "  if (!project?.conflictsWithOriginal || (!requestedNames.length && resolved.complete)) return false;",
  "  const selectedItems = resolved.items;",
  "  const canAutoManage = resolved.complete;",
  "  const listHtml = selectedItems.length",
  "    ? `<ul class=\"install-conflict-list\">${selectedItems.map(item => `<li><i class=\"fas fa-book\"></i><span>${escapeHtml(item.displayName || '原版条目')}</span></li>`).join('')}</ul>`",
  "    : '<div class=\"install-conflict-unavailable\">暂时无法读取 Creator 声明的原版条目列表。</div>';",
  "  const safetyHtml = canAutoManage",
  "    ? '<p>如果选择「是」，Workshop 会重新检查当前世界书及角色 Regex，确认匹配后才关闭所选冲突内容。以后不会按旧记录自动恢复启用状态。</p>'",
  "    : '<p>目前无法确认全部声明条目，因此 Workshop 不会自动关闭任何原版内容。你仍可以选择自己处理后继续安装。</p>';",
  "  const bodyHtml = `<div class=\"install-conflict-consent\"><div class=\"detail-warning\"><i class=\"fas fa-triangle-exclamation\"></i><div><strong>这个 DLC 声明会与原版内容冲突</strong><span>安装或更新前请确认是否要关闭冲突的世界书条目／角色 Regex。</span></div></div>${listHtml}${safetyHtml}<div class=\"install-conflict-actions\"><button class=\"btn btn-outline\" type=\"button\" data-conflict-cancel>取消</button><button class=\"btn btn-outline\" type=\"button\" data-conflict-manual>不用，我自己处理并安装</button><button class=\"btn btn-primary\" type=\"button\" data-conflict-auto${canAutoManage ? '' : ' disabled'}>是，帮我关闭并安装</button></div></div>`;",
  "  const overlay = openModal(bodyHtml, '<i class=\"fas fa-shield-halved\"></i> 安装前确认');",
  "  return new Promise(resolve => {",
  "    let settled = false;",
  "    const finish = result => {",
  "      if (settled) return;",
  "      settled = true;",
  "      if (overlay.isConnected) overlay.remove();",
  "      resolve(result);",
  "    };",
  "    overlay.querySelector('[data-conflict-cancel]')?.addEventListener('click', () => finish(null));",
  "    overlay.querySelector('.close-btn')?.addEventListener('click', () => finish(null), { once: true });",
  "    overlay.addEventListener('click', event => { if (event.target === overlay) finish(null); });",
  "    overlay.querySelector('[data-conflict-manual]')?.addEventListener('click', () => finish(false));",
  "    overlay.querySelector('[data-conflict-auto]')?.addEventListener('click', async event => {",
  "      const button = event.currentTarget;",
  "      if (button.disabled) return;",
  "      button.disabled = true;",
  "      try {",
  "        const preview = await inspectOriginalConflictChoices(project.id, project.version);",
  "        const ambiguities = Array.isArray(preview.ambiguities) ? preview.ambiguities : [];",
  "        if (!ambiguities.length) { finish(true); return; }",
  "        const choices = await chooseAmbiguousOriginalRegexes(ambiguities);",
  "        if (choices !== null) finish({ originalConflictSelections: choices });",
  "      } catch (error) {",
  "        showToast('原版 Regex 检查失败：' + (error?.message || String(error)), 'error');",
  "      } finally { if (overlay.isConnected) button.disabled = false; }",
  "    });",
  "  });",
  "}",
  "",
].join('\n');
